# Generated by Django 5.1.2 on 2024-10-25 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banques', '0008_alter_compteenbanque_taux_interet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interet',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='banques.transaction')),
            ],
            bases=('banques.transaction',),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('TRANSACTION', 'Transaction'), ('DEPOT', 'Dépot'), ('RETRAIT', 'Retrait'), ('VIREMENT', 'Virement'), ('INTERET', 'Intérêt')], default='TRANSACTION', max_length=50, verbose_name='Type'),
        ),
    ]
